[build]
  functions = "./functions"


[[redirects]]
  from = "/hola"
  to = "/.netlify/functions/hola"
  status = 200

[[redirects]]
  from = "/hello"
  to = "/.netlify/functions/hello"
  status = 200



